### PR TITLE
fix: streamlit error

### LINKED ISSUE #2: AttributeError after deploying app on Streamlit Cloud
Error on Streamlit

Traceback:

File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
File "/app/sentiment-analysis-using-svm/app.py", line 7, in <module>
    op = model.predict([ip])
File "/home/appuser/venv/lib/python3.9/site-packages/sklearn/pipeline.py", line 458, in predict
    return self.steps[-1][1].predict(Xt, **predict_params)
File "/home/appuser/venv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 810, in predict
    y = super().predict(X)
File "/home/appuser/venv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 435, in predict
    return predict(X)
File "/home/appuser/venv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 503, in _sparse_predict
    self._probA,

### PR DESCRIPTION
**Pull request by srini047**
## Related Issue

Fixes #2

## Files that have been updated

- `Sentiment_Analyser`
- `app.py`
- `requirements.txt`

## Changes that have been made
Changed the sklearn version (inconsistency) which caused the error in the streamlit development.

### CODE REVIEW

**Comment by srini047** [comment]
Check the deployed app here (to test its working): https://srini047-sentiment-analysis-using-svm-app-streamlit-dev-jx27sj.streamlit.app/

Screenshot 2022-12-24 at 1 50 21 PM

## Improvements

- Make the theme customized
- Fine-tune the model as it currently doesn't perform very well.

**Comment by jasmine1601** [comment]
@srini047 Remove the commented code from `app.py` (`lines 4-6`) and the cell containing `%%writefile app.py` in the `.ipynb` file

**Comment by srini047** [comment]
@jasmine1601 That results in an error.

```
    body = p()
NameError: name 'p' is not defined
```

**Comment by jasmine1601** [comment]
@srini047 I asked you to remove the commented code, not uncomment it.

**Comment by srini047** [comment]
@jasmine1601 Sorry for the misunderstanding. I have done the necessary changes. Please re-review my PR.

**Pull request merged**
