### PR TITLE
Added small description about analyser

### PR DESCRIPTION
**Pull request by ManasviEmmadi**
Added description about sentiment analyser in streamlit app
Related issue: #4

### CODE REVIEW

**Comment by jasmine1601** [comment]
@ManasviEmmadi Shift the description to the bottom of the app and change the description to only: "Analyzes the sentiment of input phrases"

**Comment by ManasviEmmadi** [comment]
@jasmine1601 
image
put it at the bottom.

**Comment by ManasviEmmadi** [comment]
Should i also add a color theme?

**Comment by jasmine1601** [comment]
> @jasmine1601 image put it at the bottom.

@ManasviEmmadi Okay. Did you commit the new changes?

**Comment by ManasviEmmadi** [comment]
yeah

**Pull request merged**
